import json
from core.gemini_client import GeminiClient

class PlanningAgent:
    """
    Generates a long-term growth plan for the village.
    """
    def __init__(self, gemini_client: GeminiClient):
        self.gemini_client = gemini_client

    def create_growth_plan(self, village_data: dict, analysis_results: dict) -> str:
        """
        Creates a 3, 6, and 12-month growth plan.

        Args:
            village_data: The initial structured data of the village.
            analysis_results: The analyses generated by the AnalysisAgent.

        Returns:
            A string containing the complete growth plan.
        """
        print("\nPlanning Agent: Gaon ke liye growth plan banaya ja raha hai... (Creating growth plan for the village...)")
        
        prompt = f"""
        Act as a rural development strategist. You have been provided with comprehensive data and analysis for an Indian village. Your task is to create a practical and actionable growth plan for the next year.

        **1. Village Data:**
        {json.dumps(village_data, indent=2)}

        **2. Village Analysis:**
        *   **Village Profile:** {analysis_results.get('village_profile', 'N/A')}
        *   **Problem Analysis:** {analysis_results.get('problem_analysis', 'N/A')}
        *   **Shopkeeper Insights:** {analysis_results.get('shopkeeper_insights', 'N/A')}
        *   **Customer Recommendations:** {analysis_results.get('customer_recommendations', 'N/A')}

        **Instructions:**
        Based on all the information above, create a growth plan divided into three phases:
        - **Phase 1: Short-Term (First 3 Months)**
        - **Phase 2: Mid-Term (Next 6 Months)**
        - **Phase 3: Long-Term (Next 12 Months)**

        For each phase, list 2-3 key initiatives. For each initiative, you MUST specify:
        1.  **Initiative:** A clear description of the action to be taken.
        2.  **Responsible Stakeholder:** The primary group or person responsible (e.g., Gram Panchayat, Youth Group, SHG, School Administration, Health Workers, Shopkeepers Association).
        3.  **Difficulty:** The estimated difficulty to implement (Low, Medium, High).
        4.  **Expected Impact:** A score from 1 (lowest) to 5 (highest) indicating its potential positive impact on the village.

        Format the output clearly, with distinct sections for each phase. The tone should be professional, encouraging, and practical.
        """
        
        plan = self.gemini_client.generate_text(prompt)
        print("Planning Agent: Growth plan taiyaar hai. (Growth plan is ready.)")
        return plan

if __name__ == '__main__':
    # testing the PlanningAgent directly.
    try:
        # Dummy data for testing
        dummy_village_data = {
            "village_name_and_state": "Basi, Uttar Pradesh",
            "population_approx": 5000,
            "main_occupation": "Agriculture",
            "internet_availability": "3G/4G",
            "shops_schools_hospitals": "10 shops, 2 schools, 1 clinic",
            "top_3_problems": "1. Lack of clean drinking water, 2. Irregular electricity, 3. Poor road connectivity"
        }
        
        dummy_analysis_results = {
            "village_profile": "Basi is a village of 5000 people in Uttar Pradesh, primarily dependent on agriculture. It has basic amenities like 10 shops, 2 schools, and a clinic, with moderate 3G/4G internet connectivity.",
            "problem_analysis": "The main issues are contaminated drinking water leading to health problems, frequent power cuts disrupting daily life and work, and poor roads hindering transportation.",
            "shopkeeper_insights": "Shopkeepers should stock more water purifiers, solar lamps, and phone chargers. They could also benefit from offering mobile-based services.",
            "customer_recommendations": "Villagers could form a cooperative to purchase a community water filter. Using solar-powered devices and learning basic mobile skills are also recommended."
        }

        print("--- Running PlanningAgent Test ---")
        gemini_client = GeminiClient()
        planning_agent = PlanningAgent(gemini_client)
        
        growth_plan = planning_agent.create_growth_plan(dummy_village_data, dummy_analysis_results)
        
        print("\n\n--- Generated Growth Plan ---")
        print(growth_plan)
            
    except Exception as e:
        print(f"An error occurred in the test run: {e}")
